[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rtd-test-project"
authors = [{name = "FeRD", email = "ferdnyc@gmail.com"}]
dynamic = ["version", "description"]
